[package]
name = "engine"
version = "0.1.0"
authors = ["Dominic Bertocchini <dominicbertocchini@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

 [dependencies.sdl2]
    version = "0.34"
    default-features = false
    features = ["ttf","image","mixer"]